# ~/.zlogout: executed by zsh(1) when login shell exits.
#
# Clear screen on logout for privacy (only for login shells)

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
