# Exit early for non-interactive shells
[[ $- != *i* ]] && return

export EDITOR=vim
export VISUAL=vim
export PAGER=less

# History
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth:erasedups
export HISTTIMEFORMAT='%F %T '
shopt -s histappend
shopt -s checkwinsize
shopt -s cmdhist

# Safer defaults
set -o noclobber  # Prevent accidental overwrites with >
shopt -s checkhash
shopt -s checkjobs

# Source functions first (needed for prompt)
source ~/.dotfiles/bash/functions.sh

# Prompt (simple + informative with git branch)
PS1='\u@\h:\w$(parse_git_branch)\$ '

command -v direnv >/dev/null && eval "$(direnv hook bash)"

# Add user bin directories to PATH if they exist
[ -d "$HOME/bin" ] && path-prepend "$HOME/bin"
[ -d "$HOME/.dotfiles/bin" ] && path-prepend "$HOME/.dotfiles/bin"

# Source extras
source ~/.dotfiles/bash/aliases.sh
source ~/.dotfiles/bash/env.sh
